### ISSUE TITLE
Find a gem for AMWS

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/amazon_fulfillment_integration#1]
There seem to be a few out there: https://github.com/search?l=Ruby&q=amazon+marketplace+web+services&ref=searchresults&type=Repositories&utf8=%E2%9C%93

This one looks to be the most feature complete:  https://github.com/veeqo/mws-rb

Developer documentation is here: https://developer.amazonservices.co.uk/

We'll be using the Fulfillment Inventory and Fulfillment Outbound Shipment APIs: 
https://developer.amazonservices.co.uk/gp/mws/api.html?ie=UTF8&group=fulfillment&section=inventory&version=latest

https://developer.amazonservices.co.uk/gp/mws/api.html?ie=UTF8&group=fulfillment&section=outbound&version=latest

You can test API requests here: https://mws.amazonservices.co.uk/scratchpad/index.html

**Comment by onedanshow** [comment]
Tagging @apeacox as well

**Comment by AlessioRocco** [comment]
We already did some research for another project and the best gem that I found is this https://github.com/hakanensari/peddler.
