### ISSUE TITLE
Pull inventory levels from Amazon UK warehouse

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/amazon_fulfillment_integration#2]
My assumption of how this will work:

1) Pull this endpoint every 10 minutes using the `QueryStartDateTime` param: http://docs.developer.amazonservices.com/en_US/fba_inventory/FBAInventory_ListInventorySupply.html

2) Make another request if needed (results are paginated)

3) Loop through the results, and format like so: https://support.wombat.co/hc/en-us/articles/202535230-Inventory

4) Setup cellucor.eu have to a warehouse with the same name as the `location` param used here. We can call it  `AMAZON-UK`

Tagging @apeacox  as well

**Comment by AlessioRocco** [comment]
Done.
