### ISSUE TITLE
Take orders submitted on cellucor.eu and submit to Amazon FBA UK

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/amazon_fulfillment_integration#3]
How I assume this will work:

1) cellucor.eu submits an order to Wombat

2) A flow in wombat will push the order to this endpoint

3) Take the format of a Wombat order ( https://support.wombat.co/hc/en-us/articles/202555780-Orders ) and submit it to this AMWS endpoint: http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_CreateFulfillmentOrder.html

Tagging @apeacox  as well.

Payment will still be handled on the Spree side.

**Comment by AlessioRocco** [comment]
Done
