### ISSUE TITLE
Update cellucor.eu with shipment information

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/amazon_fulfillment_integration#4]
How I think this will work:

1) Once an order has been submitted to Amazon FBA, it appears we'll have to poll using the Spree order ID (as the `SellerFulfillmentOrderId`) to get the shipment information for it: http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_GetFulfillmentOrder.html

2) Once found, parse the `FulfillmentShipment` and format it as https://support.wombat.co/hc/en-us/articles/202319984-Shipments

3) Mark the order as "shipped" somewhere in this integration's data store so that it will stop polling AMWS for it.

Tagging @apeacox  as well.

**Comment by AlessioRocco** [comment]
Done.
